name: Build C++ Project with Boost (choco)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Boost via Chocolatey
        run: choco install boost -y

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBOOST_ROOT="C:/local/boost_1_83_0"

      - name: Build
        run: |
          cd build
          cmake --build . --config Release