name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-test-dev

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Используем предустановленный Boost в GitHub Actions
          echo "Using pre-installed Boost on Windows runner"

      - name: Configure CMake
        run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: |
          cd build
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            ctest -C Release -V
          else
            ctest -V
          fi

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: build/*.deb build/*.zip build/*.tar.gz
          retention-days: 1